# Generated by Django 5.2.6 on 2025-09-20 05:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sathi_user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='user_id'),
        ),
    ]
