# Generated by Django 5.2.6 on 2025-09-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Validation', '0002_alter_sathi_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sathi_user',
            name='User_image',
        ),
    ]
